---
pool:
  name: 'Azure Pipelines'
  vmImage: ubuntu-latest

trigger:
  - master

extend:
  template: ./templates/demo-parameters.yml
  parameters:
    branch: master
    agentvmImage: ubuntu-18.04
    jdkversion: '1.8'