version: '3.9'
services:
  webservice: 
    image: nginx:1.23
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    networks:
      - webservice-net
  dbservice:
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: docker-compose-test
      MYSQL_USER: gaurav
      MYSQL_PASSWORD: gaurav
    ports:
      - target: 3306
        published: 8306
        protocol: tcp
        mode: host
    networks:
      - webservice-net
networks:
  webservice-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16