---
pool: 
  name: 'Azure Pipelines'
  vmImage: 'ubuntu-latest'

trigger:
  - main

schedules:
  - cron: "* * * * *"
    displayName: everyminute
    branches:
      include:
        - main

stages:
  - stage: build
    displayName: buildstage
    jobs:
      - job: buildjob
        displayName: mavenbuildjob
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'package'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              jdkVersionOption: '1.17'