---
- name: install tomcat
  hosts: all
  become: true
  tasks:
    - name: install java
      ansible.builtin.apt:
        name: openjdk-11-jdk
        state: latest
        update_cache: true
    - name: create tomcat group
      ansible.builtin.group:
        name: tomcat
        state: present
    - name: create tomcat user
      ansible.builtin.user:
        name: tomcat
        create_home: true
        home: /opt/tomcat/
        shell: /bin/false
        group: tomcat
    - name: download and unarchieve tomcat file
      ansible.builtin.unarchive: 
        src: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.71/bin/apache-tomcat-9.0.71.tar.gz
        dest: /opt/tomcat/
        remote_src: yes
    - name: create link for tomcat
      ansible.builtin.file:
        src: /opt/tomcat/apache-tomcat-9.0.71
        dest: /opt/tomcat/latest
        state: link
    - name: create tomcat service file 
      ansible.builtin.copy:
        src: tomcat.service
        dest: /etc/systemd/syetem/tomcat.service
    - name: create conext.xml file
      ansible.builtin.copy:
        src: conext.xml
        dest: /opt/tomcat/latest/webapps/manager/META-INF/context.xml
    - name: create conext.xml file
      ansible.builtin.copy:
        src: conext.xml
        dest: /opt/tomcat/latest/webapps/host-manager/META-INF/context.xml
    