parameters:
    - name: branch
      displayName: Git Branch
      type: string
      default: 'main'
    - name: agentvmImage
      displayName: Agent vm Image
      type: string
      default: 'ubuntu-latest'
    - name: jdkversion
      displayName: 'Java version'
      type: string
      default: '1.11'

steps:
    - task: Maven@3
      inputs: 
        mavenPOMFile: 'pom.xml'
        goals: 'package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        jdkVersionOption: ${{ parameters.jdkversion }}