parameters:
    - name: branch
      displayName: Git Branch
      type: string
      default: 'main'
    - name: agentvmImage
      displayName: Agent vm Image
      type: string
      default: 'ubuntu-latest'
    - name: jdkversion
      displayName: 'Java version'
      type: string
      default: '1.11'

steps:
    - script: echo hello