---
- name: install lamp stack in ubuntu and centos
  hosts: all
  become: yes
  tasks:

    - name: update repository
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_facts['distribution'] == "Ubuntu"
      
    - name: install apache2 and php
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: install httpd and php
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"
      when: ansible_facts['distribution'] == "CentOS"

    - name: copy php file
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html/info.php
    
    - name: start and enable service
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        state: started
        enabled: true
