---
- name: install tomcat
  hosts: all
  become: true
  tasks:
    - name: install java
      ansible.builtin.yum:
        name: java-1.8.0-openjdk-devel
        state: present
    
    - name: create group
      ansible.builtin.group:
        name: tomcat
        state: present

    - name: create user
      ansible.builtin.user:
        name: tomcat
        group: tomcat
        home: /opt/tomcat 
        shell: /bin/false