pipeline {
    agent { label 'JDK_8_11' }
    triggers { pollSCM ('*/15 * * * *') }
    parameters {
        choice(name: 'build stage', choices: ['clean', 'package', 'install'], description: 'build stage')
    }
    stages {
        stage ('vcs') {
            steps { git 'https://github.com/wakaleo/game-of-life.git' }
        }
        stage ('build') {
            tools { jdk 'JDK_8_UBUNTU' }
            steps { sh 'mvn package' }
        }
    }
}