---
- name: install and configure java
  hosts: all
  become: yes
  tasks:
  - name: find and display
    ansible.builtin.find:
      paths: /opt/tomcat/latest/bin/
      patterns: "*.sh"
    register: file_list

  - name: adding file to list
    no_log: true
    set_facts:
      Files: "{{[ item.path ]}}"
    with_items: "{{ file_list.files }}"

  - debug: var=Files