---
- name: install and configure java
  hosts: all
  become: yes
  tasks:
  - name: find and display
    ansible.builtin.find:
      paths: /opt/tomcat/latest/bin/
      patterns: "*.sh"
    register: file_list
  - name: print file list
    ansible.builtin.debug:
      var: file_list
  - name: change permission
    ansible.builtin.file:
      path: "{{ item.path }}"
      mode: u+x
    with_items:
      - "{{ file_list.files }}"