apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: apache
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  minReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hpa-apache-deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-apache-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: apache-app
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: apache-app
    spec:
      containers:
      - image: httpd
        name: hpa-apache-container
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: hpa-apache-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: apache-app
  type: LoadBalancer