apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-hpa-demo
  labels: 
    app: nginx-app-hpa-demo
spec:
  selector:
    matchLabels:
      app: nginx-app
  replicas: 2
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP