apiVersion: v1
kind: Pod
metadata:
  name: mysql-vol-demo
spec:
  containers:
    - name: mysql-container
      image: mysql:8
      env:
       - name: MYSQL_ROOT_PASSWORD
         value: rootroot
       - name: MYSQL_DATABASE
         value: employees
       - name: MYSQL_USER
         value: mysqladmin
       - name: MYSQL_PASSWORD
         value: mysqladmin
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-vol
  volumes:
    - name: mysql-vol
      persistentVolumeClaim:
        claimName: pvc-demo