---
- name: install and deploy k8s
  hosts: k8s
  become: true
  tasks:
    - name: apt update install packages to allow apt to use a repository over HTTPS
      ansible.builtin.apt:
        update_cache: true
        name:
          - ca-certificates
          - curl
          - gnupg 
          - lsb-release
        state: latest
    - name: create directory
      ansible.builtin.file:
        dest: /etc/apt/keyrings
        state: directory
    - name: copy gpg keys
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ gpg_key_dest }}"
      loop: "{{ gpg_key_src }}"
    - name: add repositories
      ansible.builtin.command: "{{ item }}"
      loop:
        - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        - echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list > /dev/null
    - name: update repo
      ansible.builtin.apt:
        update_cache: true
    - name: download cri-dockerd
      ansible.builtin.get_url:
        url: https://storage.googleapis.com/golang/getgo/installer_linux
        dest: /root/
        mode: a+x
    - name: execute installer_linux
      ansible.builtin.command: /root/installer_linux
    - name: clone git command
      ansible.builtin.git:
        repo: 'https://github.com/Mirantis/cri-dockerd.git'
        dest: /root/cri-dockerd
        clone: true
    - name: create bin dir in cri-dockerd dir
      ansible.builtin.file:
        dest: /root/cri-dockerd/bin
        state: directory
    - name: build cri-dockerd
      ansible.builtin.command: /usr/local/sbin/go build -o /root/cri-dockerd/bin/cri-dockerd
      args:
        chdir: /root/cri-dockerd/
    - name: install cri-dockerd to /usr/local/bin/
      ansible.builtin.command: /usr/bin/install -o root -g root -m 0755 bin/cri-dockerd /usr/local/bin/cri-dockerd
    