---
- name: install and deploy k8s
  hosts: all
  become: true
  tasks:
    - name: apt update install packages to allow apt to use a repository over HTTPS
      ansible.builtin.apt:
        update_cache: true
        name:
          - ca-certificates
          - curl
          - gnupg 
          - lsb-release
        state: latest
    - name: create directory
      ansible.builtin.file:
        dest: /etc/apt/keyrings
        state: directory
    - name: download gpg key
      ansible.builtin.copy: 
        remote_src: true
        src: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/