---
- name: install and deploy k8s
  hosts: all
  become: true
  tasks:
    - name: apt update install packages to allow apt to use a repository over HTTPS
      ansible.builtin.apt:
        update_cache: true
        name:
          - ca-certificates
          - curl
          - gnupg 
          - lsb-release
    - name: create directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory