apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    app: webapp
spec:
  containers:
  - name: webapp-container
    image: mmumshad/simple-webapp-mysql
    ports:
    - containerPort: 8080
      protocol: TCP
    env:
    - name: DB_Host
      value: mysql-service
    - name: DB_User
      value: root
    - name: DB_Password
      value: paswrd
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
  - nodePort: 30082
    port: 8080
    protocol: TCP
    targetPort: 8080
