---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: regapp-deployment
spec:
  replicas: 4
  selector: 
    matchLabels:
      app: regapp
  strategy: 
    type: RollingUpdate
  template: 
    metadata:
      name: regapp-pod
      labels:
        app: regapp
    spec:
      containers:
        - name: regapp-container
          image: maxpain62/regapp:latest
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: regapp-service
spec:
  type: LoadBalancer
  selector: 
    app: regapp
  ports:
    - targetPort: 8080
      port: 8080
      protocol: TCP