pipeline{
    agent any 
    stages{ 
        stage ('VCS') {
            steps {
                git url: 'https://github.com/gauravlabtesting/spring-petclinic.git', branch: 'develop'
            }
        }
        stage ('build') {
            steps {
                sh 'mvn package'
                stash name: 'spc', includes: 'target/*.jar'
            }
        }
        stage ('unstash') {
            agent { label 'deploy' }
            steps {
                unstash name: 'spc'
            }
        }
    }
}