apiVersion: v1
kind: Pod
metadata: 
  name: configmap-vol
spec:
  containers:
    - name: configmap-container
      image: alpine
      command:
        - sleep
        - 1d
      volumeMounts:
        - name: configmap-volume
          mountPath: /cm
  volumes:
    - name: configmap-volume
      configMap:
        name: comfigmap-demo