apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod3
spec:
  containers:
    - name: configmap-container
      image: alpine
      command:
        - sleep
        - 1d
      envFrom: 
        - configMapRef:
            name: comfigmap-demo